// packages/react/react-ui/src/Collapse.tsx
import type { FC, PropsWithChildren } from 'react';
import React, { useLayoutEffect, useRef, useEffect, useState } from 'react';

export type CollapseProps = PropsWithChildren<{
    isOpen: boolean;
    id?: string;
    className?: string;
    transition?: string;
    onMouseEnter?: () => void;
    onMouseLeave?: () => void;
}>;

export const Collapse: FC<CollapseProps> = function ({
    children,
    className,
    transition = 'height 250ms ease-out',
    isOpen,
    onMouseEnter,
    onMouseLeave,
}) {
    const initialState = { height: '0px', transition };
    const wrapRef = useRef<HTMLDivElement>(null);
    const [style, setStyle] = useState(initialState);

    useEffect(
        function () {
            setStyle((style) => ({ ...style, transition }));
        },
        [transition]
    );

    function open() {
        if (!wrapRef.current) {
            return;
        }
        setStyle((style) => ({
            ...style,
            height: wrapRef.current?.scrollHeight + 'px',
        }));
    }

    function close() {
        if (!wrapRef.current) {
            return;
        }
        setStyle((style) => ({
            ...style,
            height: '0px',
        }));
    }

    useLayoutEffect(() => {
        if (isOpen) {
            open();
        } else {
            close();
        }
    }, [isOpen]);

    return (
        <div
            ref={wrapRef}
            className={'react-collapse ' + className}
            style={{
                overflow: 'hidden',
                ...style,
            }}
            onMouseEnter={onMouseEnter}
            onMouseLeave={onMouseLeave}
        >
            {children}
        </div>
    );
};

// packages/vue/vue-ui/src/WalletActionButton/Collapse.tsx
import { defineComponent, reactive, ref, Teleport, watch } from 'vue';

export const Collapse = defineComponent({
    props: {
        isOpen: {
            type: Boolean,
            default: false,
        },
        telePortId: { type: String, default: '' },
        className: { type: String, default: '' },
        transition: { type: String, default: 'height 250ms ease-out' },
    },
    emits: ['mouseEnter', 'mouseLeave'],
    setup(props, { emit, slots }) {
        const style = reactive<{ height: string; transition: string }>({ height: '0px', transition: props.transition });
        function setStyle(newStyle: { height?: string; transition?: string }) {
            Object.assign(style, newStyle);
        }
        watch(
            () => props.transition,
            function () {
                Object.assign(style, {
                    transition: props.transition,
                });
            }
        );
        const wrapRef = ref<HTMLElement | null>(null);

        function open() {
            if (!wrapRef.value) {
                return;
            }
            setStyle({ height: wrapRef.value?.scrollHeight + 'px' });
        }
        function close() {
            if (!wrapRef.value) {
                return;
            }
            setStyle({ height: '0px' });
        }
        watch(
            () => props.isOpen,
            (isOpen) => {
                if (isOpen) {
                    open();
                } else {
                    close();
                }
            }
        );

        function onMouseEnter() {
            emit('mouseEnter');
        }
        function onMouseLeave() {
            emit('mouseLeave');
        }

        return () => (
            <Teleport to={`#${props.telePortId}`}>
                <div
                    ref={wrapRef}
                    class={`vue-collapse ${props.className}`}
                    style={{ overflow: 'hidden', ...style }}
                    onMouseenter={onMouseEnter}
                    onMouseleave={onMouseLeave}
                >
                    {slots.default ? slots.default() : null}
                </div>
            </Teleport>
        );
    },
});
