// packages/react/react-ui/src/WalletDisconnectButton.tsx
import { useWallet } from '@tronweb3/tronwallet-adapter-react-hooks';
import type { FC, MouseEventHandler } from 'react';
import React, { useCallback, useMemo } from 'react';
import type { ButtonProps } from './Button.js';
import { Button } from './Button.js';

export const WalletDisconnectButton: FC<ButtonProps> = ({ children, disabled, onClick, ...props }) => {
    const { wallet, disconnect, disconnecting, connected } = useWallet();

    const handleClick: MouseEventHandler<HTMLButtonElement> = useCallback(
        (event) => {
            if (onClick) onClick(event);
            // eslint-disable-next-line @typescript-eslint/no-empty-function
            if (!event.defaultPrevented) disconnect().catch(() => {});
        },
        [onClick, disconnect]
    );

    const content = useMemo(() => {
        if (children) return children;
        if (disconnecting) return 'Disconnecting ...';
        if (wallet) return 'Disconnect';
        return 'Disconnect Wallet';
    }, [children, disconnecting, wallet]);

    return (
        <Button
            data-testid="wallet-disconnect-button"
            disabled={disabled || !wallet || !connected}
            icon={wallet ? wallet.adapter.icon : ''}
            onClick={handleClick}
            {...props}
        >
            {content}
        </Button>
    );
};

// packages/vue/vue-ui/src/WalletDisconnectButton.tsx
import { useWallet } from '@tronweb3/tronwallet-adapter-vue-hooks';
import { computed, defineComponent } from 'vue';
import { Button, ButtonProps } from './Button.js';
export const WalletDisconnectButton = defineComponent({
    props: ButtonProps,
    setup(props, { slots }) {
        const { wallet, disconnect, disconnecting, connected } = useWallet();
        async function handleClick() {
            let preventDefault = false;
            if (props.onClick) {
                preventDefault = await props.onClick();
            }
            if (!preventDefault) {
                disconnect().catch(() => {
                    //
                });
            }
        }
        const content = computed(() => {
            if (slots.default) return slots.default();
            if (disconnecting.value) return 'Disconnecting ...';
            if (wallet.value) return 'Disconnect';
            return 'Disconnect Wallet';
        });
        return () => (
            <Button
                {...{ ...props, onClick: handleClick }}
                data-testid="wallet-disconnect-button"
                disabled={props.disabled || !wallet.value || !connected.value}
                icon={props.icon ? props.icon : wallet.value ? wallet.value.adapter.icon : ''}
            >
                {content.value}
            </Button>
        );
    },
});
