// packages/react/react-ui/src/WalletSelectButton.tsx
import React, { useCallback } from 'react';
import type { MouseEvent, FC } from 'react';
import { Button } from './Button.js';
import type { ButtonProps } from './Button.js';
import { useWalletModal } from './useWalletModal.js';

export const WalletSelectButton: FC<ButtonProps> = function ({ children = 'Select Wallet', onClick, ...props }) {
    const { visible, setVisible } = useWalletModal();

    const handleClick = useCallback(
        (event: MouseEvent<HTMLButtonElement>) => {
            if (onClick) onClick(event);
            if (!event.defaultPrevented) setVisible(!visible);
        },
        [onClick, setVisible, visible]
    );

    return (
        <Button data-testid="wallet-select-button" onClick={handleClick} {...props}>
            {children}
        </Button>
    );
};

// packages/vue/vue-ui/src/WalletSelectButton.tsx
import { Button } from './Button.js';
import { ButtonProps } from './Button.js';
import { useWalletModal } from './useWalletModal.js';
import { defineComponent } from 'vue';

export const WalletSelectButton = defineComponent({
    props: ButtonProps,
    setup(props, { slots }) {
        const { visible, setVisible } = useWalletModal();
        const handleClick = () => {
            let preventDefault = false;
            if (props.onClick) {
                preventDefault = props.onClick();
            }
            if (!preventDefault) setVisible(!visible.value);
        };
        return () => (
            <Button {...{ ...props, onClick: handleClick }} data-testid="wallet-select-button">
                {slots.default ? slots.default() : 'Select Wallet'}
            </Button>
        );
    },
});
