// packages/react/react-ui/src/WalletModalProvider.tsx
import React, { useState } from 'react';
import { WalletSelectModal } from './Modal/WalletSelectModal.js';
import { WalletModalContext } from './useWalletModal.js';

export function WalletModalProvider({ children, ...props }: any) {
    const [visible, setVisible] = useState(false);
    return (
        <WalletModalContext.Provider
            value={{
                visible,
                setVisible,
            }}
        >
            {children}
            {<WalletSelectModal visible={visible} onClose={() => setVisible(false)} {...props} />}
        </WalletModalContext.Provider>
    );
}

// packages/vue/vue-ui/src/WalletModalProvider.tsx
import { defineComponent, provide, readonly, ref } from 'vue';
import { WalletSelectModal } from './Modal/WalletSelectModal.js';
export const WalletModalProvider = defineComponent({
    setup(props, { slots }) {
        const visible = ref(false);
        function setVisible(v: boolean) {
            visible.value = v;
        }
        provide('TronWalletModalContext', {
            visible: readonly(visible),
            setVisible,
        });
        return () => (
            <>
                {slots.default ? slots.default() : ''}
                <WalletSelectModal visible={visible.value} onClose={() => setVisible(false)}></WalletSelectModal>
            </>
        );
    },
});
