// packages/react/react-ui/src/WalletItem.tsx
import { AdapterState } from '@tronweb3/tronwallet-abstract-adapter';
import type { Wallet } from '@tronweb3/tronwallet-adapter-react-hooks';
import type { FC } from 'react';
import React from 'react';
import { Button } from './Button.js';

export interface WalletItemProps {
    onClick: () => void;
    wallet: Wallet;
}

export const WalletItem: FC<WalletItemProps> = ({ onClick, wallet }) => {
    return (
        <div className="adapter-wallet-item">
            <Button onClick={onClick} icon={wallet.adapter.icon} tabIndex={0}>
                {wallet.adapter.name}
                <span className="status-text">{wallet.state !== AdapterState.NotFound ? 'Detected' : 'NotFound'}</span>
            </Button>
        </div>
    );
};

// packages/vue/vue-ui/src/WalletItem.tsx
import { AdapterState } from '@tronweb3/tronwallet-abstract-adapter';
import type { Wallet } from '@tronweb3/tronwallet-adapter-vue-hooks';
import { defineComponent } from 'vue';
import type { PropType } from 'vue';
import { Button } from './Button.js';

export interface WalletItemProps {
    onClick: () => void;
    wallet: Wallet;
}
export const WalletItem = defineComponent({
    props: {
        wallet: {
            type: Object as PropType<Wallet>,
            required: true,
        },
    },
    emits: ['click'],
    setup(props, { emit }) {
        function onClick() {
            emit('click');
        }
        return () => (
            <div class="adapter-wallet-item">
                <Button onClick={onClick} icon={props.wallet.adapter.icon} tabIndex={0}>
                    {props.wallet.adapter.name}
                    <span class="status-text">
                        {props.wallet.state !== AdapterState.NotFound ? 'Detected' : 'NotFound'}
                    </span>
                </Button>
            </div>
        );
    },
});
